version: '3'

services:
  mongo:
    image: mongo
    container_name: ca-mongo
    ports:
      ["27017"]
  bindaas:
    build: "https://github.com/sharmalab/bindaas.git#:docker"
    depends_on:
      -"mongo"
    container_name: ca-data
    ports: ["9099:9099"]
  iip:
    build: "https://github.com/camicroscope/iipImage.git"
    container_name: ca-iip
    ports: ["4010:4010"]
  viewer:
    build: "https://github.com/camicroscope/caMicroscope.git#refactor"
    container_name: ca-front
    ports: ["80:8088"]
